// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6LF4OyNBFrdnYyn_XxHOXbZomUOmFjIA',
    appId: '1:776888666049:android:8309186764edb52a79d140',
    messagingSenderId: '776888666049',
    projectId: 'lab12-eca89',
    storageBucket: 'lab12-eca89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4nxbWQqB85lc-knsgMqzYgzIZuzRmDBg',
    appId: '1:776888666049:ios:0cc5547156f0e0f079d140',
    messagingSenderId: '776888666049',
    projectId: 'lab12-eca89',
    storageBucket: 'lab12-eca89.appspot.com',
    iosClientId: '776888666049-ll0sejoamddle4d79p1erdu993rphkek.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4nxbWQqB85lc-knsgMqzYgzIZuzRmDBg',
    appId: '1:776888666049:ios:0cc5547156f0e0f079d140',
    messagingSenderId: '776888666049',
    projectId: 'lab12-eca89',
    storageBucket: 'lab12-eca89.appspot.com',
    iosClientId: '776888666049-ll0sejoamddle4d79p1erdu993rphkek.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab12',
  );
}
